- hosts: webservers
  become: true

  tasks:
    - name: Configure password policies
      lineinfile:
        path: /etc/pam.d/common-password
        regexp: '^password\s+requisite\s+pam_passwdqc.so'
        line: 'password requisite pam_passwdqc.so retry=3 min=12 max=24 minclass=4'
        state: present
      notify:
        - restart ssh

  handlers:
    - name: restart ssh
      service:
        name: sshd
        state: restarted
